"""admin departments roles sla approval routing

Revision ID: fa74c3024f58
Revises: b8316dd51efa
Create Date: 2026-08-25 03:14:26.890026
"""
from alembic import op
import sqlalchemy as sa


revision = 'fa74c3024f58'
down_revision = 'b8316dd51efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_default',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub', sa.Text(), nullable=False),
    sa.Column('employee_code', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('approvers', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('sequence', 'any_of')", name='ck_approval_rules_mode'),
    sa.CheckConstraint("priority IS NULL OR priority IN ('low', 'normal', 'high', 'urgent')", name='ck_approval_rules_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('local_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub', sa.Text(), nullable=False),
    sa.Column('employee_code', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('is_agent', sa.Boolean(), nullable=False),
    sa.Column('is_department_manager', sa.Boolean(), nullable=False),
    sa.Column('is_approver', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_roles_sub'), 'local_roles', ['sub'], unique=True)
    op.create_table('sla_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name='ck_sla_configs_priority'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'priority', name='uq_sla_configs_department_priority')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sla_configs')
    op.drop_index(op.f('ix_local_roles_sub'), table_name='local_roles')
    op.drop_table('local_roles')
    op.drop_table('departments')
    op.drop_table('approval_rules')
    op.drop_table('approval_default')
    # ### end Alembic commands ###
