"""INT-1 — Service Desk TRUE SSO, proven end to end in `AUTH_MODE=http`, offline.

This is the deliverable the whole cross-host SSO decision rests on (see the product-owner
note in the C1 brief and `handoff/c1-sso.md`): MM OS and its services live on *different*
hosts, so SSO cannot lean on a shared parent cookie. The real mechanism is the launch
token-handoff — MM OS mints a short-lived, single-audience RS256 token; the service verifies
it OFFLINE via JWKS, checks the deny-list, and sets its OWN session cookie. This test proves
exactly that path, with nothing faked except the network boundary.

What is real here, not stubbed:
  * a real RS256 keypair (generated by `backend/app/security` on first use);
  * the token is minted by the *production* `backend/app/security.mint_service_token`;
  * verification runs through the *production* client kit `packages/mmos-client-py`
    (`mmos_client.core.MMOS._verify` -> `_verify.verify_token`, the exact ordered checklist
    in docs/04-auth-flow.md);
  * the accept/session handoff and the fail-closed allowlist middleware are the real
    `MMOS.install(app)` routes every service uses;
  * the protected route is Service Desk's own `GET /api/tickets/mine`, guarded by the
    production `app.mmos_seam.get_current_user` seam in its `http` branch.

The ONLY thing faked is the MM OS HTTP surface (JWKS + the revocation feed), injected at the
`httpx` boundary via `httpx.MockTransport` — the same technique every other suite in this
repo uses, and the same boundary A1/A4 fake Google and live MM OS at. No socket is opened.

Asserts, per the brief:
  (a) POST /_mmos/session with a valid launch token sets the service session cookie;
  (b) a protected route then works, by cookie and by bearer;
  (c) an expired / wrong-audience / wrong-signature token is rejected (401);
  (d) once the token's jti is on the deny-list, the next request is revoked within one poll.
"""
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import tempfile
import time
from pathlib import Path
from types import SimpleNamespace

import httpx
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

_REPO_ROOT = Path(__file__).resolve().parents[2]

# ── make packages/mmos-client-py importable (the shared client kit) ──────────────────────
_CLIENT_PKG = _REPO_ROOT / "packages" / "mmos-client-py"
if str(_CLIENT_PKG) not in sys.path:
    sys.path.insert(0, str(_CLIENT_PKG))

# ── back the MM OS signing key with a throwaway temp file BEFORE importing backend.security.
# backend/app/security loads (or generates) the RSA key at import time from
# MMOS_SIGNING_KEY_PATH. Point it at a writable temp path so it self-generates a real 2048-bit
# keypair for the test rather than reaching for /run/secrets/... (which does not exist here).
_KEY_PATH = Path(tempfile.gettempdir()) / "mmos-int1" / f"int1_signing_key_{os.getpid()}.pem"
_KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MMOS_SIGNING_KEY_ID", "mmos-int1-test")
os.environ["MMOS_SIGNING_KEY_PATH"] = str(_KEY_PATH)
os.environ.setdefault("MMOS_ISSUER", "https://os.int1.test")

# ── load backend/app.{config,security} under a DISTINCT package name ──────────────────────
# Both backend/app and servicedesk/app are packages literally named `app`; the servicedesk
# conftest has already imported servicedesk's `app`, so a plain `import app.security` would
# resolve to the wrong one. Load the two backend modules we need under a synthetic package
# name so there is no collision. security.py only uses relative imports (`from .config import
# settings`), so this resolves cleanly with the package's __path__ set below.
_BACKEND_APP = _REPO_ROOT / "backend" / "app"
_PKG = "mmos_backend"
if _PKG not in sys.modules:
    _spec = importlib.util.spec_from_file_location(
        _PKG, _BACKEND_APP / "__init__.py", submodule_search_locations=[str(_BACKEND_APP)]
    )
    _mod = importlib.util.module_from_spec(_spec)
    sys.modules[_PKG] = _mod
    _spec.loader.exec_module(_mod)

backend_security = importlib.import_module(f"{_PKG}.security")
backend_cfg = importlib.import_module(f"{_PKG}.config").settings()

# ── the service under test ────────────────────────────────────────────────────────────────
from app import mmos_seam  # noqa: E402  (servicedesk's app)
from app.routers import tickets  # noqa: E402

SLUG = "servicedesk"
OS_URL = backend_cfg.issuer  # the client kit derives the JWKS URL from os_url


# ── a stand-in MM OS user/employee for mint_service_token (duck-typed, no ORM needed) ──────
def _mint(service_slug: str = SLUG, roles=("requester",)):
    """Mint a launch token exactly the way production does — through
    backend/app/security.mint_service_token. Returns (token, jti)."""
    user = SimpleNamespace(id="int1-user-0001", is_platform_admin=False)
    employee = SimpleNamespace(
        employee_code="MM88",
        work_email=None,
        full_name="MAMATESH UDAY NAIK",
        hr_department="Projects",
        division="Projects",
        band="L2",
        approval_level="L1 (Associate)",
    )
    token, jti, _ttl = backend_security.mint_service_token(
        user=user, employee=employee, service_slug=service_slug, roles=list(roles)
    )
    return token, jti


def _raw_encode(claims: dict, *, kid: str | None = None) -> str:
    """Sign arbitrary claims with the SAME private key the mint path uses, for the negative
    cases (expired / wrong-audience) that mint_service_token would not itself produce."""
    from jose import jwt

    return jwt.encode(
        claims,
        backend_security._private_pem,
        algorithm="RS256",
        headers={"kid": kid or backend_cfg.signing_key_id},
    )


def _base_claims(**overrides) -> dict:
    now = int(time.time())
    claims = {
        "iss": backend_cfg.issuer,
        "sub": "user:int1-user-0001",
        "aud": SLUG,
        "jti": "int1-jti-fixed",
        "iat": now,
        "exp": now + 900,
        "emp": "MM88",
        "email": None,
        "name": "MAMATESH UDAY NAIK",
        "dept": "Projects",
        "division": "Projects",
        "band": "L2",
        "approval_level": "L1 (Associate)",
        "roles": ["requester"],
        "platform_admin": False,
    }
    claims.update(overrides)
    return claims


# ── the http-mode Service Desk app, wired the way app/main.py wires it in production ────────
@pytest.fixture
def http_sso(monkeypatch):
    """Stand up Service Desk in AUTH_MODE=http against a faked MM OS.

    The faked MM OS serves only two surfaces, at the httpx boundary:
      * GET /.well-known/jwks.json  -> the real public JWKS for the mint key;
      * GET /api/agent/revocations  -> the revocation feed the deny-list poller reads.
    Everything else is the production code path.
    """
    revocations = {"revoked_subjects": [], "revoked_jti": []}

    def handler(request: httpx.Request) -> httpx.Response:
        path = request.url.path
        if path == "/.well-known/jwks.json":
            return httpx.Response(200, json=backend_security.jwks())
        if path == "/api/agent/revocations":
            return httpx.Response(
                200,
                json={
                    "revoked_subjects": list(revocations["revoked_subjects"]),
                    "revoked_jti": list(revocations["revoked_jti"]),
                    "now": "2026-08-28T00:00:00Z",
                    "poll_after_seconds": 60,
                },
            )
        if path == "/api/agent/heartbeat":
            return httpx.Response(200, json={"ok": True})
        return httpx.Response(404, json={"error": "not_found", "path": path})

    from mmos_client.core import MMOS

    mock_client = httpx.Client(base_url=OS_URL, transport=httpx.MockTransport(handler))
    mmos = MMOS(
        slug=SLUG,
        os_url=OS_URL,
        service_key="int1-service-key",
        issuer=backend_cfg.issuer,
        cookie_name=mmos_seam.COOKIE_NAME,  # "servicedesk_mmos_at"
        http_client=mock_client,
        clock_skew_seconds=60,
    )
    # Inject the double so both the kit's middleware AND the seam's own http verify path
    # (get_current_user -> _decode_http_token -> get_real_mmos()._verify) use this instance.
    mmos_seam.set_real_mmos_for_testing(mmos)

    # Force the seam into its http branch without needing a full production settings object —
    # verify_token() reads only settings().auth_mode on this path.
    monkeypatch.setattr(
        mmos_seam, "settings", lambda: SimpleNamespace(auth_mode="http", dev_secret="unused")
    )

    app = FastAPI()
    # The real client kit: /_mmos/accept (GET), /_mmos/session (POST, sets the cookie),
    # /_mmos/health, the fail-closed allowlist middleware, and the flat-error handler.
    # start_background=False so the poller/heartbeat threads do not run on a timer — this test
    # drives poll_once() itself, deterministically.
    mmos.install(app, start_background=False)
    # A genuine Service Desk protected endpoint, mounted exactly as app/main.py does.
    app.include_router(tickets.router, prefix="/api")

    # https base_url on purpose: the kit sets the session cookie `Secure` (correct — Service
    # Desk runs behind TLS in production), so an http TestClient would silently drop it from
    # its jar and never send it back. Speaking https to the ASGI app is the faithful mirror of
    # the real deployment and lets the cookie round-trip be proven honestly.
    client = TestClient(app, base_url="https://testserver")
    try:
        yield SimpleNamespace(client=client, mmos=mmos, revocations=revocations)
    finally:
        client.close()
        mock_client.close()
        mmos_seam.set_real_mmos_for_testing(None)


# ── (a) + (b): the happy path — accept sets a cookie, protected routes then work ───────────
def test_accept_sets_cookie_and_protected_route_works(http_sso):
    token, _jti = _mint()

    # (a) the launch handoff: POST /_mmos/session with the token sets the service session cookie.
    r = http_sso.client.post("/_mmos/session", json={"token": token})
    assert r.status_code == 200, r.text
    assert mmos_seam.COOKIE_NAME in r.cookies, "no service session cookie was set"

    # the GET /_mmos/accept page that the browser lands on first is served by the real kit too.
    assert http_sso.client.get("/_mmos/accept").status_code == 200

    # (b) the cookie now carries a real session: a protected Service Desk route works with it.
    # TestClient has stored the Set-Cookie from the accept call above.
    r = http_sso.client.get("/api/tickets/mine")
    assert r.status_code == 200, r.text
    assert r.json() == []

    # and the same token works as a bearer credential (fresh client, no cookie jar).
    bare = TestClient(http_sso.client.app, base_url="https://testserver")
    r = bare.get("/api/tickets/mine", headers={"Authorization": f"Bearer {token}"})
    assert r.status_code == 200, r.text
    bare.close()


def test_no_token_is_rejected(http_sso):
    # The allowlist middleware fails closed: an un-listed path with no token is 401.
    bare = TestClient(http_sso.client.app, base_url="https://testserver")
    r = bare.get("/api/tickets/mine")
    assert r.status_code == 401
    assert r.json()["error"] in ("missing_token", "invalid_state")
    bare.close()


# ── (c): expired / wrong-audience / wrong-signature are all rejected ───────────────────────
def test_expired_token_rejected(http_sso):
    now = int(time.time())
    expired = _raw_encode(_base_claims(iat=now - 2000, exp=now - 1000))
    r = http_sso.client.post("/_mmos/session", json={"token": expired})
    assert r.status_code == 401
    assert r.json()["error"] == "expired"


def test_wrong_audience_token_rejected(http_sso):
    # A perfectly-signed token minted for another service must not open this one (docs/04 §4).
    other, _jti = _mint(service_slug="itemcode")
    r = http_sso.client.post("/_mmos/session", json={"token": other})
    assert r.status_code == 401
    assert r.json()["error"] == "bad_audience"


def test_tampered_signature_rejected(http_sso):
    token, _jti = _mint()
    head, payload, sig = token.split(".")
    # Flip a character in the signature segment so verification fails.
    bad_sig = ("A" if sig[0] != "A" else "B") + sig[1:]
    tampered = f"{head}.{payload}.{bad_sig}"
    r = http_sso.client.post("/_mmos/session", json={"token": tampered})
    assert r.status_code == 401
    assert r.json()["error"] == "bad_signature"


def test_wrong_signing_key_rejected(http_sso):
    # A token signed by a DIFFERENT key but carrying the trusted kid must be rejected — the
    # JWKS entry decides, not the header's claimed kid.
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    rogue = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    rogue_pem = rogue.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    from jose import jwt

    forged = jwt.encode(
        _base_claims(), rogue_pem, algorithm="RS256", headers={"kid": backend_cfg.signing_key_id}
    )
    r = http_sso.client.post("/_mmos/session", json={"token": forged})
    assert r.status_code == 401
    assert r.json()["error"] == "bad_signature"


# ── (d): deny-list revocation takes effect within one poll ─────────────────────────────────
def test_revocation_within_poll_window(http_sso):
    token, jti = _mint()

    # Establish a working session first.
    assert http_sso.client.post("/_mmos/session", json={"token": token}).status_code == 200
    assert http_sso.client.get("/api/tickets/mine").status_code == 200

    # An initial poll (nothing revoked yet) leaves access intact.
    assert http_sso.mmos.poller.poll_once() is True
    assert http_sso.client.get("/api/tickets/mine").status_code == 200

    # MM OS now revokes this token's jti (as POST /api/admin/grants DELETE / kill would).
    http_sso.revocations["revoked_jti"].append(jti)

    # One poll cycle — the same call the background thread makes every poll_after_seconds —
    # merges the revocation into the service's local deny-list.
    assert http_sso.mmos.poller.poll_once() is True

    # The very next request from that token is now refused, offline, with no MM OS round trip.
    r = http_sso.client.get("/api/tickets/mine")
    assert r.status_code == 401
    assert r.json()["error"] == "revoked"


def test_subject_revocation_within_poll_window(http_sso):
    token, _jti = _mint()
    assert http_sso.client.post("/_mmos/session", json={"token": token}).status_code == 200
    assert http_sso.client.get("/api/tickets/mine").status_code == 200

    # Revoke by subject (the guaranteed block that deactivating a user writes — docs/04).
    http_sso.revocations["revoked_subjects"].append({"sub": "user:int1-user-0001"})
    assert http_sso.mmos.poller.poll_once() is True

    r = http_sso.client.get("/api/tickets/mine")
    assert r.status_code == 401
    assert r.json()["error"] == "revoked"
