"""initial schema

Hand-written, not autogenerated — there is no live Postgres on the build machine for
`alembic revision --autogenerate` to inspect (see handoff/a1-identity.md). Mirrors
backend/app/models.py column-for-column, and layers in the CHECK constraints and partial
indexes from docs/02-data-model.md that models.py does not itself declare (SQLAlchemy indexes
declared only via raw DDL don't need an ORM-side __table_args__ entry to exist in the
database). Two small models.py-vs-docs differences are noted inline where they occur; see
`## Contract objections` in the handoff for the full explanation of each.

Revision ID: 0001
Revises:
Create Date: 2026-08-24

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_pk() -> sa.Column:
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ── people ───────────────────────────────────────────────────────────
    op.create_table(
        "employees",
        _uuid_pk(),
        sa.Column("employee_code", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("work_email", sa.Text(), nullable=True),
        sa.Column("hr_department", sa.Text(), nullable=False),
        sa.Column("division", sa.Text(), nullable=False),
        sa.Column("job_title", sa.Text(), nullable=False),
        sa.Column("band", sa.String(length=8), nullable=False),
        sa.Column("approval_level", sa.Text(), nullable=True),
        sa.Column("manager_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("is_approver", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["manager_id"], ["employees.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("employee_code", name="uq_employees_employee_code"),
        sa.UniqueConstraint("work_email", name="uq_employees_work_email"),
        sa.CheckConstraint("status IN ('active','suspended','exited')", name="employee_status"),
    )
    op.create_index("ix_employees_dept", "employees", ["hr_department"])
    op.create_index("ix_employees_manager_id", "employees", ["manager_id"])

    op.create_table(
        "users",
        _uuid_pk(),
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("login_email", sa.Text(), nullable=True),
        sa.Column("auth_type", sa.String(length=16), nullable=False, server_default="google"),
        sa.Column("pin_hash", sa.Text(), nullable=True),
        sa.Column("pin_set_at", sa.DateTime(timezone=True), nullable=True),
        # failed_pin_attempts / locked_until: in models.py but not in the docs/02 DDL — the
        # PIN lockout mechanics in docs/04 need somewhere to live. See Contract objections.
        sa.Column("failed_pin_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("employee_id", name="uq_users_employee_id"),
        sa.UniqueConstraint("login_email", name="uq_users_login_email"),
        sa.CheckConstraint("auth_type IN ('google','local_pin')", name="user_auth_type"),
        sa.CheckConstraint("auth_type <> 'local_pin' OR pin_hash IS NOT NULL", name="pin_required"),
        sa.CheckConstraint("auth_type <> 'google' OR login_email IS NOT NULL", name="email_required"),
        sa.CheckConstraint("NOT (auth_type = 'local_pin' AND is_platform_admin)", name="no_pin_admins"),
    )

    # ── service registry ─────────────────────────────────────────────────
    op.create_table(
        "services",
        _uuid_pk(),
        sa.Column("slug", sa.String(length=48), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=False, server_default="internal"),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=48), nullable=True),
        sa.Column("launch_mode", sa.String(length=16), nullable=False, server_default="handoff"),
        sa.Column("has_public_surface", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("public_url", sa.Text(), nullable=True),
        sa.Column("health_url", sa.Text(), nullable=True),
        sa.Column("owner_employee_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("service_key_hash", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="100"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["owner_employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("slug", name="uq_services_slug"),
        sa.CheckConstraint("launch_mode IN ('handoff','embed','external')", name="launch_mode_valid"),
    )

    op.create_table(
        "service_roles",
        _uuid_pk(),
        sa.Column("service_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("service_id", "key", name="uq_service_role"),
    )

    # ── the permission model ─────────────────────────────────────────────
    op.create_table(
        "grants",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("service_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("service_role_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("granted_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_role_id"], ["service_roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("user_id", "service_id", name="uq_grant_user_service"),
    )
    op.create_index("ix_grants_service", "grants", ["service_id"])

    # ── sessions and revocation ──────────────────────────────────────────
    op.create_table(
        "sessions",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        # models.py calls this `token_hash`; docs/02 calls it `refresh_token_hash`. Same
        # column, naming-only difference — see Contract objections.
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
    )
    # Partial index from docs/02 — only live (unrevoked) sessions are looked up by user.
    op.create_index(
        "ix_sessions_user_live",
        "sessions",
        ["user_id"],
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    op.create_table(
        "revocations",
        _uuid_pk(),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("service_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("jti", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("revoked_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        # docs/02 gives this a DEFAULT (now() + interval '2 hours'); models.py declares the
        # column NOT NULL with no default at all. Kept NOT NULL with the documented default
        # applied server-side too, so a bare INSERT without the app supplying it still works.
        sa.Column(
            "purge_after",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("(now() + interval '2 hours')"),
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revoked_by"], ["users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_revocations_at", "revocations", ["revoked_at"])

    # ── LLM control plane ────────────────────────────────────────────────
    op.create_table(
        "llm_registrations",
        _uuid_pk(),
        sa.Column("service_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("key_present", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("disabled_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        # models.py adds disabled_reason (not in docs/02) — see Contract objections.
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["disabled_by"], ["users.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("service_id", name="uq_llm_registrations_service_id"),
    )

    op.create_table(
        "llm_usage_daily",
        _uuid_pk(),
        sa.Column("service_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("input_tokens", sa.Numeric(20, 0), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Numeric(20, 0), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("service_id", "day", name="uq_usage_service_day"),
    )

    # ── audit ────────────────────────────────────────────────────────────
    op.create_table(
        "audit_log",
        _uuid_pk(),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("service_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="SET NULL"),
    )
    # docs/02 asks for created_at DESC and a composite (actor_user_id, created_at DESC)
    # index; models.py only declares a plain ascending index on created_at.
    op.create_index("ix_audit_created", "audit_log", [sa.text("created_at DESC")])
    op.create_index(
        "ix_audit_actor_created", "audit_log", ["actor_user_id", sa.text("created_at DESC")]
    )


def downgrade() -> None:
    # Reverse dependency order. Extension is left in place — dropping it is not this
    # migration's business and other databases on the same Postgres instance may use it.
    op.drop_table("audit_log")
    op.drop_table("llm_usage_daily")
    op.drop_table("llm_registrations")
    op.drop_table("revocations")
    op.drop_table("sessions")
    op.drop_table("grants")
    op.drop_table("service_roles")
    op.drop_table("services")
    op.drop_table("users")
    op.drop_table("employees")
