"""Real MiniMines employee names for a demo -- see backend/app/seed.py's
"dump_demo_fixture" for how this file is produced and "seed_from_fixture" for how it is
consumed.

The Coolify container cannot reach Employee_Role_Access_Mapping.xlsx (it lives outside the
repo on purpose -- it holds every employee's personal contact detail), so this file is a
snapshot the container seeds itself from with no spreadsheet present.

Contains REAL employee full names, for a demo, in a private repo. Deliberately excludes
every email address: PIN login needs none, and 49 of the sheet's 73 "Work Email" values are
personal gmail.com addresses that must never enter git or an internet-facing box. The one
exception is the platform admin's "itadmin@m-mines.com", a role address, not a person --
seed_platform_admin() creates that one the same way it always has; it is not repeated here.

DELETE THIS FILE once the real batched rollout (reading the spreadsheet directly, from a
box that can reach it) replaces it.

Generated by `python -m app.seed --dump-demo-fixture`, from select_demo_batch() /
_pick_demo_roles() in app/seed.py, against the real spreadsheet. Re-run that command to
regenerate after the sheet changes -- do not hand-edit DEMO_PEOPLE or DEMO_LOGIN_ROLES.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DemoPerson:
    employee_code: str
    full_name: str
    hr_department: str
    division: str
    job_title: str
    band: str
    approval_level: str | None
    manager_employee_code: str | None


DEMO_PEOPLE: list[DemoPerson] = [
    DemoPerson('MM103', 'Bhanu Prakash Tiwari', 'N-Hub', 'Production', 'Asst. Manager N-HUB', 'L2', 'L2 (Sr Asst Mgr)', 'MM68'),
    DemoPerson('MM65', 'Neeraj Kumar', 'N-Hub', 'Production', 'Shift In-charge', 'L1S', 'L1 (Associate)', None),
    DemoPerson('MM118', 'Puttaraju B K', 'N-Hub', 'Production', 'Jr. Electrical Engineer', 'L1J', 'Operational', None),
    DemoPerson('MM68', 'Sunith S', 'P-Hub', 'Production', 'Asst. Manager HUB', 'L3', 'L2 (Sr Asst Mgr)', 'MM05'),
    DemoPerson('MM07', 'Simbu Rabadia', 'P-Hub', 'Production', 'Asst. Manager HUB', 'L2', 'L2 (Sr Asst Mgr)', 'MM68'),
    DemoPerson('MM47', 'Jerin Thomas', 'P-Hub', 'Production', 'Shift In-charge', 'L1S', 'L1 (Associate)', None),
    DemoPerson('MM81', 'Chandrashekhar Keshav Kalvit', 'Projects', 'Corporate', 'Project Head', 'L4', 'L4 (Div Head)', None),
    DemoPerson('MM120', 'Rishabh Srivastav', 'Projects', 'Projects', 'Electrical Manager', 'L2', 'L2', None),
    DemoPerson('MM88', 'MAMATESH UDAY NAIK', 'Projects', 'Projects', 'Project Engineer/Site engineer', 'L2', 'L1 (Associate)', 'MM81'),
    DemoPerson('MM09', 'Rajesh Kumar', 'QA/QC', 'R&D', 'Asst. Manager QA/QC', 'L2', 'L2 (Sr Asst Mgr)', None),
    DemoPerson('MM50', 'Deekshith P', 'QA/QC', 'R&D', 'Lab Analyst / Associate', 'L1S', 'L1 (Associate)', 'MM09'),
    DemoPerson('MM52', 'Shreyas Dinkar Bure', 'QA/QC', 'R&D', 'Lab Analyst / Associate', 'L1J', 'L1 (Associate)', None),
    DemoPerson('MM37', 'Sushmita T', 'Material Management', 'BD & Operations', 'Sr. Stores Associate', 'L1S', 'L1 (Associate)', None),
    DemoPerson('MM100', 'Gowtham N G', 'Material Management', 'BD & Operations', 'Sr. Stores Associate', 'L1S', 'L1 (Associate)', None),
    DemoPerson('MM101', 'Rohith L R', 'Material Management', 'BD & Operations', 'Sr. Logistics Associate', 'L1S', 'L1 (Associate)', None),
    DemoPerson('MM04', 'Manish Chauhan', 'Business Development', 'BD & Operations', 'BD Procurement Manager', 'L3', 'L3 (HOD)', None),
    DemoPerson('MM45', 'HANUMAN SINGH L', 'Business Development', 'BD & Operations', 'BD Procurement Manager', 'L3', 'L3 (HOD)', None),
    DemoPerson('MM05', 'Mandaleshvar Sharma', 'P-Spoke', 'Production', 'Head of SPOKE', 'L4', 'L3 (HOD)', None),
    DemoPerson('MM19', 'Deepak Dixit', 'P-Spoke', 'Production', 'Operators Day/Night Shift & Discharging Operators', 'L1S', 'Operational', None),
    DemoPerson('MM119', 'Md Arsalan', 'StratOps', 'CXO Office', 'Process Automation Engineer IT', 'L1J', 'L1J', None),
    DemoPerson('MM33', 'Hardhik Pendurthi', 'StratOps', 'Corporate', 'Strategy & Operations', 'NON L', 'Oversight', None),
    DemoPerson('MM66', 'Jagadevappa', 'Second Life', 'Production', 'Second Life', 'L1S', 'Operational', None),
    DemoPerson('MM106', 'Diwakar Dixit', 'Second Life', 'Production', 'Testing & Dismantling Operators', 'L1S', 'Operational', None),
]

# Which of the above play the four non-admin demo logins (the platform admin is
# synthetic and always seeded by seed_platform_admin(), not listed here).
DEMO_LOGIN_ROLES: dict[str, str] = {
    'agent': 'MM05',
    'approver': 'MM81',
    'requester_1': 'MM88',
    'requester_2': 'MM33',
}
